### ISSUE TITLE
Problem when a service is unregistered [Karaf]

### ISSUE THREAD

**Issue by jhernandezgt** [hstaudacher/osgi-jax-rs-connector#102]
Based on the example of jersey as a http service [Http Service Example](https://github.com/jersey/jersey/tree/master/examples/osgi-http-service) i'm able to get working with this, but when the bundle is unregistered gets an error
```
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.examples.osgihttpservice.JerseyApplication not found by com.eclipsesource.jaxrs.jersey-all [92]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)[:1.7.0_75]
    at java.lang.Class.forName0(Native Method)[:1.7.0_75]
    at java.lang.Class.forName(Class.java:191)[:1.7.0_75]
    at org.glassfish.jersey.internal.util.ReflectionHelper$7.run(ReflectionHelper.java:407)[92:com.eclipsesource.jaxrs.jersey-all:2.17.0]
    at org.glassfish.jersey.internal.util.ReflectionHelper$7.run(ReflectionHelper.java:397)[92:com.eclipsesource.jaxrs.jersey-all:2.17.0]
    at java.security.AccessController.doPrivileged(Native Method)[:1.7.0_75]
    at org.glassfish.jersey.servlet.WebComponent.createResourceConfig(WebComponent.java:491)[92:com.eclipsesource.jaxrs.jersey-all:2.17.0]
```

What this cause is when the bundle is updated unregister fails and it have to be restarted manually

**Comment by hstaudacher** [comment]
Where does this class `org.glassfish.jersey.examples.osgihttpservice.JerseyApplication` life? In your application bundle?

**Comment by hstaudacher** [comment]
no response so I will close this issue. Please feel free to reopen.
