### ISSUE TITLE
Bind Exception during application upgrade

### ISSUE THREAD

**Issue by ramkumarnn** [hstaudacher/osgi-jax-rs-connector#203]
HI Team,

 When we upgrade our version of Rest application, we get the below exception in our logs saying **java.net.BindException: Address already in use**. There is no traffic disturbance observed. Please add your thoughts.

java.net.BindException: Address already in use
               at sun.nio.ch.Net.bind0(Native Method)
               at sun.nio.ch.Net.bind(Net.java:433)
               at sun.nio.ch.Net.bind(Net.java:425)
               at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
               at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
               at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351)
               at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319)
               at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
               at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
               at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
               at org.eclipse.jetty.server.Server.doStart(Server.java:401)
               at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
               at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$1.start(JettyServerImpl.java:350)
               at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:250)
               at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:221)
               at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:205)
               at org.ops4j.pax.web.service.internal.HttpServiceProxy.registerServlet(HttpServiceProxy.java:65)
               at com.eclipsesource.jaxrs.publisher.internal.JerseyContext.registerServlet(JerseyContext.java:159)
               at com.eclipsesource.jaxrs.publisher.internal.JerseyContext.registerApplication(JerseyContext.java:137)
               at com.eclipsesource.jaxrs.publisher.internal.JerseyContext.registerServletWhenNotAlreadyRegistered(JerseyContext.java:129)
               at com.eclipsesource.jaxrs.publisher.internal.JerseyContext.addResource(JerseyContext.java:76)
               at com.eclipsesource.jaxrs.publisher.internal.JAXRSConnector.registerResource(JAXRSConnector.java:189)
               at com.eclipsesource.jaxrs.publisher.internal.JAXRSConnector.registerResource(JAXRSConnector.java:171)
               at com.eclipsesource.jaxrs.publisher.internal.JAXRSConnector.clearCache(JAXRSConnector.java:132)
               at com.eclipsesource.jaxrs.publisher.internal.JAXRSConnector.doAddHttpService(JAXRSConnector.java:124)
               at com.eclipsesource.jaxrs.publisher.internal.JAXRSConnector.addHttpService(JAXRSConnector.java:63)

**Comment by ramkumarnn** [comment]
Do we have an update on this ??
