### ISSUE TITLE
Enable support for Jersey Bean Validation JSR 349

### ISSUE THREAD

**Issue by philiptran** [hstaudacher/osgi-jax-rs-connector#56]
Hi,

First of all, thanks for the great Jersey connector. It saves my days. 

I try to look for documentation on how to enable support for Jersey Bean Validation JSR349 but no avail. I checked the jersey-all bundle and it seems that this feature is not currently supported. Is there any plan to support JSR 349? Thank you.

**Comment by Asisranjan** [comment]
Hi hstaudacher ,

Integrated jersey bean validation. It works fine. But getting below exception..The exceptionmapper is not invoked though i have one for this.

javax.servlet.ServletException: javax.validation.ConstraintViolationException
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)

Thanks
Asisranjan Nayak
