### ISSUE TITLE
NoClassDefFoundError: javax/annotation/Priority

### ISSUE THREAD

**Issue by mhshams** [hstaudacher/osgi-jax-rs-connector#77]
I am trying to follow the karaf example with the stable versions (released in maven central) of the artifacts, but keep getting following error.  

(The "javax.annotation" is provided by other bundle in the container.)

```
2015-01-26 20:56:45,672 | WARN  | FelixStartLevel  | AbstractLifeCycle                | 46 - org.eclipse.jetty.aggregate.jetty-all-server - 8.1.15.v20140411 | FAILED org.ops4j.pax.web.service.spi.model.ServletModel-2: java.lang.NoClassDefFoundError: javax/annotation/Priority
java.lang.NoClassDefFoundError: javax/annotation/Priority
	at org.glassfish.jersey.model.internal.ComponentBag.modelFor(ComponentBag.java:483)
	at org.glassfish.jersey.model.internal.ComponentBag.access$100(ComponentBag.java:89)
	at org.glassfish.jersey.model.internal.ComponentBag$5.call(ComponentBag.java:408)
	at org.glassfish.jersey.model.internal.ComponentBag$5.call(ComponentBag.java:398)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.model.internal.ComponentBag.registerModel(ComponentBag.java:398)
	at org.glassfish.jersey.model.internal.ComponentBag.register(ComponentBag.java:309)
	at org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:463)
	at org.glassfish.jersey.server.ResourceConfig.register(ResourceConfig.java:448)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ResourceConfig.registerInstances(ResourceConfig.java:545)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig$3.run(ResourceConfig.java:1197)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:289)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:286)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:286)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.registerComponentsOf(ResourceConfig.java:1190)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1164)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1153)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1149)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:318)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:285)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:310)[75:com.eclipsesource.jaxrs.jersey-all:2.10.1]
	at org.glassfish.
```

any idea how to solve this issue?

**Comment by maggu2810** [comment]
I have the same problem here. Any suggestions how to solve this?

**Comment by maggu2810** [comment]
Got it working after adding javax.annotation to import-packet.

**Comment by mhshams** [comment]
@maggu2810  you fixed by adding import package to which bundle?

**Comment by maggu2810** [comment]
I thought it would be solved, but it wasn't.

**Comment by hstaudacher** [comment]
I'm do not know well the the karaf integration but maybe you need the javax.annotation bundle started?

**Comment by maggu2810** [comment]
Your bundle com.eclipsesource.jaxrs.jersey-all exports javax.annotation and is active...

**Comment by hstaudacher** [comment]
yes I know. And it works well with Equinox. Bu just to let you know, the com.eclipsesource.jaxrs.jersey-all bundle isa convenient bundle. The only thing the jax-rs connector needs are some package exported by Jersey. I was sick adding all 15 bundles or so and decided to provide the all bundle. But maybe you need to add the jersey bundles directly from maven central instead of using the all bundle.

As I said, the all bundle is just are packaging of the jersey bundles.

**Comment by maggu2810** [comment]
Do not know why this is working using equinox, perhaps this is relevant:
https://wiki.eclipse.org/index.php/Equinox_Boot_Delegation

Will try to use the jersey bundles directly and report the results.

**Comment by hstaudacher** [comment]
There is also a maven build to create the all-bundle: https://github.com/hstaudacher/osgi-jax-rs-connector/tree/master/build/com.eclipsesource.jaxrs.jersey.all

Maybe you have a better idea how to create it... the current status is the first iteration, so it's far from perfect ;)

**Comment by mhshams** [comment]
@hstaudacher looking at pom file, I think the problem is that your are not importing "javax.annotation". 

javax.annoation is provided by other bundles and jersey is a consumer only. so I believe it should import the package. 

I will try to update the pom and build it locally, to see if can solve the issue.

**Comment by maggu2810** [comment]
https://issues.apache.org/jira/browse/KARAF-2660

**Comment by maggu2810** [comment]
There was no class definition:
__java.lang.NoClassDefFoundError__: javax/annotation/Priority

So, uncommenct the stuff in the jre.properties of karaf is enough.

My errors are gone.

**Comment by mhshams** [comment]
@maggu2810  thanks for the info. Updating jre.properties solved my issue two.
I am using jre-8, so in jre-8 updated the javax.annotation version to 1.1 (was 1.2) solved the issue.
