### ISSUE TITLE
Exception when running connector in karaf and shuting down

### ISSUE THREAD

**Issue by hstaudacher** [hstaudacher/osgi-jax-rs-connector#8]
When the connector is active in a karaf instance und you type "shutdown -f" into the console the following exception occurs:

```java
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:514)
	at org.apache.felix.framework.BundleContextImpl.getBundles(BundleContextImpl.java:197)
	at org.glassfish.hk2.osgiresourcelocator.ResourceFinderImpl.findEntry1(ResourceFinderImpl.java:67)
	at org.glassfish.hk2.osgiresourcelocator.ResourceFinder.findEntry(ResourceFinder.java:71)
	at org.glassfish.jersey.internal.l10n.Localizer.localize(Localizer.java:116)
	at org.glassfish.jersey.server.internal.LocalizationMessages.INIT_MSG(LocalizationMessages.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:295)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:146)
	at org.glassfish.jersey.server.ApplicationHandler$3.run(ApplicationHandler.java:265)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:210)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:207)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:226)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:207)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:262)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:266)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:568)
	at com.eclipsesource.jaxrs.connector.internal.JerseyContext.removeResource(JerseyContext.java:104)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.removeResourcesFromContext(JAXRSConnector.java:176)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.doRemoveResource(JAXRSConnector.java:169)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.removeResource(JAXRSConnector.java:161)
	at com.eclipsesource.jaxrs.connector.internal.ResourceTracker.removedService(ResourceTracker.java:58)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:956)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:902)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:338)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceRemoved(DependencyManager.java:346)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceChanged(DependencyManager.java:253)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:338)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceRemoved(DependencyManager.java:346)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceChanged(DependencyManager.java:253)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:338)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceRemoved(DependencyManager.java:346)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceChanged(DependencyManager.java:253)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:338)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceRemoved(DependencyManager.java:346)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceChanged(DependencyManager.java:253)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:338)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceRemoved(DependencyManager.java:346)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceChanged(DependencyManager.java:253)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:338)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceRemoved(DependencyManager.java:346)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceChanged(DependencyManager.java:253)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:338)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceRemoved(DependencyManager.java:346)
	at org.apache.felix.scr.impl.manager.DependencyManager.serviceChanged(DependencyManager.java:253)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.disposeInternal(AbstractComponentManager.java:357)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.dispose(AbstractComponentManager.java:196)
	at org.apache.felix.scr.impl.config.ConfiguredComponentHolder.disposeComponents(ConfiguredComponentHolder.java:299)
	at org.apache.felix.scr.impl.BundleComponentActivator.dispose(BundleComponentActivator.java:319)
	at org.apache.felix.scr.impl.Activator.disposeComponents(Activator.java:340)
	at org.apache.felix.scr.impl.Activator.bundleChanged(Activator.java:207)
	at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:868)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:789)
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:514)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4244)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2351)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1214)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:295)
	at java.lang.Thread.run(Thread.java:722)
ERROR: Bundle com.eclipsesource.jaxrs.connector [63] EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Invalid BundleContext.)
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:514)
	at org.apache.felix.framework.BundleContextImpl.getBundles(BundleContextImpl.java:197)
	at org.glassfish.hk2.osgiresourcelocator.ResourceFinderImpl.findEntry1(ResourceFinderImpl.java:67)
	at org.glassfish.hk2.osgiresourcelocator.ResourceFinder.findEntry(ResourceFinder.java:71)
	at org.glassfish.jersey.internal.l10n.Localizer.localize(Localizer.java:116)
	at org.glassfish.jersey.server.internal.LocalizationMessages.INIT_MSG(LocalizationMessages.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:295)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:146)
	at org.glassfish.jersey.server.ApplicationHandler$3.run(ApplicationHandler.java:265)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:210)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:207)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:226)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:207)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:262)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:266)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:568)
	at com.eclipsesource.jaxrs.connector.internal.JerseyContext.removeResource(JerseyContext.java:104)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.removeResourcesFromContext(JAXRSConnector.java:176)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.doRemoveResource(JAXRSConnector.java:169)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.removeResource(JAXRSConnector.java:161)
	at com.eclipsesource.jaxrs.connector.internal.ResourceTracker.removedService(ResourceTracker.java:58)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:956)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:902)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.disposeInternal(AbstractComponentManager.java:357)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.dispose(AbstractComponentManager.java:196)
	at org.apache.felix.scr.impl.config.ConfiguredComponentHolder.disposeComponents(ConfiguredComponentHolder.java:299)
	at org.apache.felix.scr.impl.BundleComponentActivator.dispose(BundleComponentActivator.java:319)
	at org.apache.felix.scr.impl.Activator.disposeComponents(Activator.java:340)
	at org.apache.felix.scr.impl.Activator.bundleChanged(Activator.java:207)
	at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:868)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:789)
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:514)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4244)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2351)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1214)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:295)
	at java.lang.Thread.run(Thread.java:722)
ERROR: Bundle com.eclipsesource.jaxrs.connector [63] EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Invalid BundleContext.)
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:514)
	at org.apache.felix.framework.BundleContextImpl.getBundles(BundleContextImpl.java:197)
	at org.glassfish.hk2.osgiresourcelocator.ResourceFinderImpl.findEntry1(ResourceFinderImpl.java:67)
	at org.glassfish.hk2.osgiresourcelocator.ResourceFinder.findEntry(ResourceFinder.java:71)
	at org.glassfish.jersey.internal.l10n.Localizer.localize(Localizer.java:116)
	at org.glassfish.jersey.server.internal.LocalizationMessages.INIT_MSG(LocalizationMessages.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:295)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:146)
	at org.glassfish.jersey.server.ApplicationHandler$3.run(ApplicationHandler.java:265)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:210)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:207)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:226)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:207)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:262)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:266)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:568)
	at com.eclipsesource.jaxrs.connector.internal.JerseyContext.removeResource(JerseyContext.java:104)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.removeResourcesFromContext(JAXRSConnector.java:176)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.doRemoveResource(JAXRSConnector.java:169)
	at com.eclipsesource.jaxrs.connector.internal.JAXRSConnector.removeResource(JAXRSConnector.java:161)
	at com.eclipsesource.jaxrs.connector.internal.ResourceTracker.removedService(ResourceTracker.java:58)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:956)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:902)
	at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
	at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4260)
	at org.apache.felix.framework.Felix.access$000(Felix.java:74)
	at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:390)
	at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:148)
	at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterComponentService(AbstractComponentManager.java:470)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$Satisfied.deactivate(AbstractComponentManager.java:1074)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.disposeInternal(AbstractComponentManager.java:357)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.dispose(AbstractComponentManager.java:196)
	at org.apache.felix.scr.impl.config.ConfiguredComponentHolder.disposeComponents(ConfiguredComponentHolder.java:299)
	at org.apache.felix.scr.impl.BundleComponentActivator.dispose(BundleComponentActivator.java:319)
	at org.apache.felix.scr.impl.Activator.disposeComponents(Activator.java:340)
	at org.apache.felix.scr.impl.Activator.bundleChanged(Activator.java:207)
	at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:868)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:789)
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:514)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4244)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2351)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1214)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:295)
	at java.lang.Thread.run(Thread.java:722)
```

**Comment by hstaudacher** [comment]
Is this still valid? Can some karaf users confirm?

**Comment by hstaudacher** [comment]
Closing because it seems not an issue anymore.
